substitutions:
  name: "geyser"
  friendly_name: "Geyser Thermostat"
  project_name: "thermostats"
  project_version: "1.0"

packages:
  common: !include .common.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  on_boot:
    - priority: 90
      then:
      # make sure the geyser is in a known state at startup
      - switch.turn_off: main_relay
      # Default to running the geyser in Home mode
      - script.execute: geyser_on

esp32:
  board: nodemcu-32s

logger:
  # It's in the ceiling, nobody is listening to the UART
  baud_rate: 0
  level: DEBUG

web_server:
  port: 80

captive_portal:

binary_sensor:
  # single main button that also puts device into flash mode when held on boot
  # For someone in the ceiling, this can be used to turn the climate control
  # into OFF or HEAT modes. It does NOT directly control the relay.
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button0
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - if:
            condition:
              lambda: |-
                return id(geyser_climate).mode != CLIMATE_MODE_OFF;
            then:
              - logger.log: "Button deactivates climate control"
              - climate.control:
                  id: geyser_climate
                  mode: "OFF"
            else:
              - logger.log: "Button activates climate control"
              - climate.control:
                  id: geyser_climate
                  mode: "HEAT"

switch:
  # template switch to represent the main relay
  # this is synchronised with the RED LED
  # Note: this is controlled by the climate entity, and is not exposed
  # for direct manipulation, otherwise it could be left on permanently
  - platform: template
    id: main_relay
    name: Relay
    turn_on_action:
      - button.press: main_relay_on
      - light.turn_on: onoff_led
    turn_off_action:
      - button.press: main_relay_off
      - light.turn_off: onoff_led
    assumed_state: True
    optimistic: True
    restore_mode: ALWAYS_OFF

  - platform: output
    name: Sensor Power
    id: sensor_power
    output: sensor_power_output
    restore_mode: ALWAYS_ON

output:
  # Ideally, these two relay GPIOs should be interlocked to prevent
  # simultaneous operation. ESPhome currently does not support
  # interlocks at an output: level, or even at a button: level
  # BE CAREFUL!
  - platform: gpio 
    id: main_relay_on_output
    pin:
      number: GPIO19
      inverted: true

  - platform: gpio 
    id: main_relay_off_output
    pin:
      number: GPIO22
      inverted: true

  - platform: ledc 
    id: red_led_output
    pin:
      number: GPIO16
      inverted: true

  - platform: ledc 
    id: green_led_output
    pin:
      number: GPIO13
      inverted: true

  # This is needed to power the external sensor.
  # It receives 3v3 from this pin, which is pulled up on boot.
  - platform: gpio
    pin: GPIO27
    id: sensor_power_output
    
button:
  # See note above about interlocks!
  - platform: output
    id: main_relay_on
    output: main_relay_on_output
    duration: 1000ms

  - platform: output
    id: main_relay_off
    output: main_relay_off_output
    duration: 1000ms

# The middle (blue) LED is used as wifi status indicator.
status_led:
  pin:
    number: GPIO15
    inverted: true

light:
  # Leftmost (red) LED that's used to indicate the relay being on/off
  - platform: binary
    id: onoff_led
    output: red_led_output
    internal: true

  # Rightmost (green) LED used to indicate climate control being active
  - platform: binary
    id: auto_led
    output: green_led_output
    internal: true

dallas:
  pin: GPIO25
  update_interval: 10s

sensor:
  # Geyser temperature
  # Has some failsafes to disable climate control if the temperature
  # being reported is unreasonable. Below 10C suggests that the ATTiny85
  # is either not connected to the thermistor, or is otherwise reporting
  # incorrect values, and should be investigated.
  #
  # NOTE: This can be overridden, but care should be taken when doing so
  # because these only apply when the temperature ENTERS these ranges
  # If it REMAINS in the range, and climate is turned on manually, these
  # failsafes will not apply!
  - platform: dallas
    address: 0x1e11223344550028
    id: temp
    name: "Temperature"
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6
    on_value_range:
      - below: 0.0
        then:
          - logger.log: "Temperature too low, disabling climate!"
          - climate.control:
              id: geyser_climate
              mode: "OFF"
          - switch.turn_off: main_relay
      - above: 75.0
        then:
          - logger.log: "Temperature too high, disabling climate!"
          - climate.control:
              id: geyser_climate
              mode: "OFF"
          - switch.turn_off: main_relay

  # The THR320 appears to run quite hot, let's just keep an eye on it
  - platform: internal_temperature
    name: "Internal Temperature"

climate:
  - platform: thermostat
    id: geyser_climate
    name: "Climate"
    sensor: temp
    visual:
      min_temperature: 40C
      max_temperature: 75C
      temperature_step:
        target_temperature: 1
        current_temperature: 1
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 55C
        mode: heat
      - name: Boost
        default_target_temperature_low: 70C
        mode: heat
      - name: Eco
        default_target_temperature_low: 45C
        mode: heat
    min_heating_off_time: 0s
    min_heating_run_time: 60s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: main_relay
    idle_action:
      - switch.turn_off: main_relay
    heat_deadband: 2 # how many degrees can we go under the temp before starting to heat
    heat_overrun: 2 # how many degrees can we go over the temp before stopping
    off_mode:
      - switch.turn_off: main_relay
    on_state:
    - if:
        condition:
          lambda: |-
            return id(geyser_climate).mode == CLIMATE_MODE_OFF;
        then:
          - logger.log: "Climate control OFF"
          - light.turn_off: auto_led
    - if:
        condition:
          lambda: |-
            return id(geyser_climate).mode == CLIMATE_MODE_HEAT;
        then:
          - logger.log: "Climate control ON"
          - light.turn_on: auto_led

script:
  - id: geyser_on
    then:
      - delay: 60s
      - if:
          condition:
            not:
              api.connected:
          then:
            - climate.control:
                id: geyser_climate
                preset: "Home"

