/******************************************************************************
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2023 Joseph Kroesche
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *****************************************************************************/

#include <stdint.h>

/** @addtogroup therm Thermistor
 *
 * This file was generated by https://github.com/kroesche/thermistor_lookup
 *
 * Generated on 2023-03-22 11:58:59.037387,<br/>
 * for a thermistor circuit with the following parameters:
 *
 * |Parameter |Value                         |
 * |----------|------------------------------|
 * |Input File|example.json                  |
 * |Board     |ATtiny85 geyserwise           |
 * |Thermistor|unknown                       |
 * |Tstart    |40                            |
 * |Tstop     |100                           |
 * |Tstep     |5                             |
 * |Tnominal  |25                            |
 * |Rnominal  |10000                         |
 * |Rpulldown |10000                         |
 * |beta      |4200                          |
 * |counts    |1023                          |
 *
 * @{
 */

static const uint16_t therm_table[] =
{
    678, // [ 0] C=40 R=5089
    724, // [ 1] C=45 R=4121
    766, // [ 2] C=50 R=3359
    802, // [ 3] C=55 R=2755
    834, // [ 4] C=60 R=2273
    861, // [ 5] C=65 R=1886
    884, // [ 6] C=70 R=1574
    904, // [ 7] C=75 R=1320
    921, // [ 8] C=80 R=1113
    935, // [ 9] C=85 R=942
    947, // [10] C=90 R=802
    957, // [11] C=95 R=685
};

#define T_AT_IDX(idx) (40 + ((idx) * 5))
#define T_STEP (5)
#define T_LAST_IDX (11)

// Calculate temperature using lookup table.
// See header file for API description
int16_t adc_to_temp(uint16_t adc)
{
    uint16_t idx;
    int16_t adc0;
    int16_t adc1;
    int16_t temp0 = 0; // prevent g++ warning

    if (adc < therm_table[0])
    {
        adc0 = therm_table[0];
        adc1 = therm_table[1];
        temp0 = T_AT_IDX(0);
    }
    else if (adc >= therm_table[T_LAST_IDX])
    {
        adc0 = therm_table[T_LAST_IDX - 1];
        adc1 = therm_table[T_LAST_IDX];
        temp0 = T_AT_IDX(T_LAST_IDX - 1);
    }

    else
    {
        for (idx = 0; idx < T_LAST_IDX; ++idx)
        {
            adc0 = therm_table[idx];
            adc1 = therm_table[idx + 1];
            if (adc < adc1)
            {
                temp0 = T_AT_IDX(idx);
                break;
            }
        }
    }

    int16_t delta = (int16_t)adc - adc0;
    int16_t range = adc1 - adc0;
    int16_t half_digit = range >> 1;

    int16_t temp = delta * T_STEP + half_digit;
    temp /= range;
    temp += temp0;

    return temp;
}
